#ifndef SELECTPROJECTWINDOW_H
#define SELECTPROJECTWINDOW_H

#include <QMainWindow>

#include "String.h"
#include "SelectProjectWindowAutoGenerated.h"

class SelectProjectWindow :
        public QObject,
        public Ui_SelectProjectWindow
{
    Q_OBJECT

public:
    SelectProjectWindow();

    static String ExecAndGetProjectFilepath(QMainWindow *window, QApplication *app);
    static SelectProjectWindow *GetInstance();
    QMainWindow* GetMainWindow() const;

public slots:
    void OnCreateNewProject();
    void OnLoadProject();
    void OnClosed();

private:
    static SelectProjectWindow *s_instance;
    String m_loadedProjectFile = "";
    QMainWindow *m_window = nullptr;
    bool m_directlyClosedByUser = false;
};

#endif // SELECTPROJECTWINDOW_H
