#ifndef WINDOWMAIN_H
#define WINDOWMAIN_H

#include "Bang.h"

#include "Logger.h"
#include "WindowMainAutoGenerated.h"

extern int var;

/**
 *  This will be a singleton shared amongst ALL *.o and *.so
 *  Cross-library shared singleton
 */
class QApplication;
class WindowMain : public Ui_WindowMain
{

private:
    WindowMain() : Ui_WindowMain() {}

    static WindowMain *win;
    static WindowMain **winPointer;

    QMainWindow *mainWindow = nullptr;
    QApplication *app = nullptr;

public:

    /**
     * @brief This must be called by main() in the mainBinary.
     * This method will register the WindowMain singleton into the
     * SingletonManager, for later use in shared libraries.
     * @return The created Singleton,
     */
    static void InitFromMainBinary(QMainWindow *window, QApplication *app);

    static WindowMain *GetInstance();
    static QMainWindow *GetMainWindow();
    QApplication *GetApplication() const;

};

#endif // WINDOWMAIN_H
