include(../BangCommon.pri)
system(rm -f Makefile)
system(rm -f .donePreprocess)
system(cd $$PWD/.. ; sh ./scripts/preprocessHeaders.sh)

TEMPLATE = lib
INCLUDEPATH += ../include
QT += core gui opengl widgets

DoPreprocess = .donePreprocess
DoPreprocess.commands = cd $$PWD/.. ; \
                        sh ./scripts/preprocessHeaders.sh ; \
                        touch .donePreprocess
QMAKE_EXTRA_TARGETS += DoPreprocess
PRE_TARGETDEPS += DoPreprocess

CONFIG += staticlib

TARGET = $$BIN_DIR/lib/Bang

LIBS = -L$$BIN_DIR/lib/ -lBangDataStructures $$LIBS
PRE_TARGETDEPS += $$BIN_DIR/lib/libBangDataStructures.a

MOC_DIR = ../src/Qt_MOCs/

UI_DIR  = ../include/Bang

EDITOR {
    FORMS   += ../EngineAssets/EditorWindow.ui
    FORMS   += ../EngineAssets/SelectProjectWindow.ui
}

SOURCES += \
    ../src/Engine/General/Time.cpp \
    ../src/Engine/Math/AABox.cpp \
    ../src/Engine/Math/Sphere.cpp \
    ../src/Engine/GameObjects/GameObject.cpp \
    ../src/Engine/GameObjects/Scene.cpp \
    ../src/Engine/Graphics/General/Texture.cpp \
    ../src/Engine/Graphics/General/VAO.cpp \
    ../src/Engine/Graphics/General/VBO.cpp \
    ../src/Engine/Components/Transform.cpp \
    ../src/Engine/Components/Component.cpp \
    ../src/Engine/Components/MeshRenderer.cpp \
    ../src/Engine/Components/Camera.cpp \
    ../src/Engine/Assets/Asset.cpp \
    ../src/Engine/Assets/Mesh.cpp \
    ../src/Engine/Assets/Material.cpp \
    ../src/Engine/Components/Behaviour.cpp \
    ../src/Engine/Assets/Texture2D.cpp \
    ../src/Engine/Assets/Prefab.cpp \
    ../src/Engine/IO/General/AssetsManager.cpp \
    ../src/Engine/General/Input.cpp \
    ../src/Engine/IO/Files/TextFile.cpp \
    ../src/Engine/Components/LineRenderer.cpp \
    ../src/Engine/Components/Renderer.cpp \
    ../src/Engine/General/SystemUtils.cpp \
    ../src/Engine/General/SingletonManager.cpp \
    ../src/Engine/Components/CircleRenderer.cpp \
    ../src/Engine/Components/SingleLineRenderer.cpp \
    ../src/Engine/Assets/MeshFactory.cpp \
    ../src/Engine/General/ICloneable.cpp \
    ../src/Editor/General/Screen.cpp \
    ../src/Engine/Components/DirectionalLight.cpp \
    ../src/Engine/Components/Light.cpp \
    ../src/Editor/General/GameObjectClipboard.cpp \
    ../src/Engine/Components/PointLight.cpp \
    ../src/Editor/General/Application.cpp \
    ../src/Engine/General/SceneManager.cpp \
    ../src/Engine/Components/Canvas.cpp \
    ../src/Engine/Components/UIImage.cpp \
    ../src/Engine/Components/UIRenderer.cpp \
    ../src/Engine/Graphics/General/FontSheetCreator.cpp \
    ../src/Engine/Assets/Font.cpp \
    ../src/Engine/Components/UIText.cpp \
    ../src/Engine/IO/General/EngineConfig.cpp \
    ../src/Engine/Assets/AudioClip.cpp \
    ../src/Engine/Components/AudioSource.cpp \
    ../src/Engine/Audio/AudioManager.cpp \
    ../src/Engine/Audio/AudioPlayerRunnable.cpp \
    ../src/Engine/Debug/Gizmos.cpp \
    ../src/Engine/Debug/Debug.cpp \
    ../src/Engine/Debug/Chrono.cpp \
    ../src/Engine/IO/Files/FileReader.cpp \
    ../src/Engine/Graphics/Buffers/Framebuffer.cpp \
    ../src/Engine/Graphics/Buffers/GBuffer.cpp \
    ../src/Engine/Graphics/Shaders/Shader.cpp \
    ../src/Engine/Graphics/Shaders/ShaderProgram.cpp \
    ../src/Engine/Graphics/GraphicPipeline/GraphicPipeline.cpp \
    ../src/Engine/IO/Files/ImageFile.cpp \
    ../src/Engine/IO/Behaviours/BehaviourManager.cpp \
    ../src/Engine/IO/XML/XMLAttribute.cpp \
    ../src/Engine/IO/XML/XMLNode.cpp \
    ../src/Engine/IO/XML/XMLParser.cpp \
    ../src/Engine/IO/XML/XMLProperty.cpp \
    ../src/Editor/Windows/IWindow.cpp \
    ../src/Editor/Windows/GameWindow.cpp \
    ../src/Engine/Components/AudioListener.cpp \
    ../src/Engine/IO/Behaviours/BehaviourManagerStatus.cpp \
    ../src/Engine/Components/RectTransform.cpp \
    ../src/Editor/General/Cursor.cpp \
    ../src/Engine/Graphics/General/RenderTexture.cpp \
    ../src/Engine/General/Object.cpp \
    ../src/Engine/Debug/GraphicPipelineDebugger.cpp \
    ../src/Engine/Graphics/GraphicPipeline/GraphicPipeline.cpp \
    ../src/Engine/Graphics/GraphicPipeline/GPPass_SP_DeferredLights.cpp \
    ../src/Engine/Graphics/GraphicPipeline/GPPass_G_Gizmos.cpp \
    ../src/Engine/Graphics/General/GLContext.cpp \
    ../src/Engine/Graphics/General/GL.cpp \
    ../src/Engine/Compiler/CodePreprocessor.cpp \
    ../src/Engine/Graphics/Shaders/ShaderPreprocessor.cpp \
    ../src/Engine/IO/Project/ProjectManager.cpp \
    ../src/Engine/IO/Project/Project.cpp \
    ../src/Engine/Graphics/GraphicPipeline/GPPass_G.cpp \
    ../src/Engine/Graphics/GraphicPipeline/GPPass.cpp \
    ../src/Engine/Graphics/General/GLObject.cpp \
    ../src/Engine/Debug/ChronoGL.cpp \
    ../src/Engine/IO/General/SerializableObject.cpp \
    ../src/Engine/Graphics/GraphicPipeline/TextureUnitManager.cpp \
    ../src/Editor/General/Shortcut.cpp \
    ../src/Engine/IO/Files/ExtensionManager.cpp \
    ../src/Editor/General/IconManager.cpp \
    ../src/Engine/Graphics/General/Image.cpp \
    ../src/Engine/Components/CircleCulledRenderer.cpp \
    ../src/Engine/IO/Files/PrefabFile.cpp \
    ../src/Engine/IO/Files/SoundFile.cpp \
    ../src/Engine/Audio/AnonymousAudioPlayer.cpp \
    ../src/Engine/Graphics/Shaders/ShaderManager.cpp \
    ../src/Engine/Components/PostProcessEffect.cpp \
    ../src/Engine/Graphics/GraphicPipeline/GPPass_SP_PostProcessEffects.cpp \
    ../src/Engine/IO/Files/ModelFile.cpp \
    ../src/Engine/IO/Files/MeshFile.cpp \
    ../src/Engine/IO/Files/Texture2DFile.cpp \
    ../src/Engine/IO/Files/ShaderProgramFile.cpp \
    ../src/Engine/IO/Files/MaterialFile.cpp \
    ../src/Engine/IO/Files/AudioClipFile.cpp \
    ../src/Engine/IO/Files/FontFile.cpp \
    ../src/Engine/IO/General/Paths.cpp \
    ../src/Engine/Graphics/GraphicPipeline/GPPass_RenderLayer.cpp \
    ../src/Engine/Compiler/BangPreprocessor/BangPreprocessor.cpp \
    ../src/Engine/Compiler/BangPreprocessor/BPReflectedStruct.cpp \
    ../src/Engine/Compiler/Compiler.cpp \
    ../src/Engine/Compiler/BangCompiler.cpp \
    ../src/Engine/Compiler/BangPreprocessor/BPReflectedVariable.cpp \
    ../src/Engine/IO/Files/BFile.cpp \
    ../src/Engine/Compiler/BangCompilerAsyncJob.cpp

HEADERS += \
    ../src/Editor/General/Application.h \
    ../src/Editor/General/Screen.h \
    ../src/Engine/Math/Rect.h \
    ../src/Engine/General/IToString.h \
    ../src/Engine/General/ISceneEventListener.h \
    ../src/Engine/GameObjects/GameObject.h \
    ../src/Engine/GameObjects/Scene.h \
    ../src/Engine/Graphics/General/Texture.h \
    ../src/Engine/Graphics/General/VAO.h \
    ../src/Engine/Graphics/General/VBO.h \
    ../src/Engine/Components/Transform.h \
    ../src/Engine/Components/Component.h \
    ../src/Engine/Components/MeshRenderer.h \
    ../src/Engine/Components/Camera.h \
    ../src/Engine/Assets/Asset.h \
    ../src/Engine/Assets/Material.h \
    ../src/Engine/Assets/Mesh.h \
    ../src/Engine/Components/Behaviour.h \
    ../src/Engine/Assets/Texture2D.h \
    ../src/Engine/Assets/Prefab.h \
    ../include/Bang/Bang.h \
    ../src/Engine/IO/General/AssetsManager.h \
    ../src/Engine/General/Input.h \
    ../src/Engine/Components/LineRenderer.h \
    ../src/Engine/Components/Renderer.h \
    ../src/Engine/Math/Vector3.h \
    ../src/Engine/Math/Quaternion.h \
    ../src/Engine/Math/Matrix4.h \
    ../src/Engine/Math/Sphere.h \
    ../src/Engine/General/SystemUtils.h \
    ../src/Engine/General/SingletonManager.h \
    ../src/Engine/Components/CircleRenderer.h \
    ../src/Engine/Components/SingleLineRenderer.h \
    ../src/Engine/Assets/MeshFactory.h \
    ../src/Engine/General/ICloneable.h \
    ../src/Engine/Components/DirectionalLight.h \
    ../src/Engine/Components/Light.h \
    ../src/Engine/Components/PointLight.h \
    ../src/Engine/Math/Vector4.h \
    ../src/Engine/Math/Vector2.h \
    ../src/Engine/Math/Color.h \
    ../src/Engine/General/SceneManager.h \
    ../src/Engine/Components/Canvas.h \
    ../src/Engine/Components/UIImage.h \
    ../src/Engine/Components/UIRenderer.h \
    ../src/Engine/Graphics/General/FontSheetCreator.h \
    ../src/Engine/Assets/Font.h \
    ../src/Engine/Components/UIText.h \
    ../src/Engine/IO/General/EngineConfig.h \
    ../src/Engine/Math/AABox.h \
    ../src/Engine/Assets/AudioClip.h \
    ../src/Engine/Components/AudioSource.h \
    ../src/Engine/Audio/AudioManager.h \
    ../src/Engine/Audio/AudioPlayerRunnable.h \
    ../src/Engine/DataStructures/Array.h \
    ../src/Engine/DataStructures/List.h \
    ../src/Engine/DataStructures/Map.h \
    ../src/Engine/DataStructures/Property.h \
    ../src/Engine/DataStructures/String.h \
    ../src/Engine/DataStructures/NamedEnum.h \
    ../src/Engine/Debug/Chrono.h \
    ../src/Engine/Debug/Debug.h \
    ../src/Engine/Debug/Gizmos.h \
    ../src/Engine/General/Time.h \
    ../src/Engine/DataStructures/Timer.h \
    ../src/Engine/Graphics/Buffers/Framebuffer.h \
    ../src/Engine/Graphics/Buffers/GBuffer.h \
    ../src/Engine/Graphics/Shaders/Shader.h \
    ../src/Engine/Graphics/Shaders/ShaderProgram.h \
    ../src/Engine/IO/Behaviours/BehaviourManager.h \
    ../src/Engine/IO/Files/FileReader.h \
    ../src/Engine/IO/Files/ImageFile.h \
    ../src/Engine/IO/XML/XMLAttribute.h \
    ../src/Engine/IO/XML/XMLNode.h \
    ../src/Engine/IO/XML/XMLParser.h \
    ../src/Engine/IO/XML/XMLProperty.h \
    ../src/Engine/IO/Files/TextFile.h \
    ../src/Engine/Math/Math.h \
    ../src/Engine/Math/Random.h \
    ../src/Engine/IO/Files/ExtensionManager.h \
    ../src/Engine/Components/AudioListener.h \
    ../src/Engine/IO/Behaviours/BehaviourManagerStatus.h \
    ../src/Engine/Components/RectTransform.h \
    ../src/Engine/Graphics/General/RenderTexture.h \
    ../src/Engine/General/Object.h \
    ../src/Engine/Debug/GraphicPipelineDebugger.h \
    ../src/Engine/Graphics/GraphicPipeline/GraphicPipeline.h \
    ../src/Engine/Graphics/GraphicPipeline/GPPass_SP_DeferredLights.h \
    ../src/Engine/Graphics/GraphicPipeline/GPPass_G_Gizmos.h \
    ../src/Engine/Graphics/General/GLContext.h \
    ../src/Engine/Graphics/General/GL.h \
    ../src/Engine/DataStructures/TypeMap.h \
    ../src/Engine/Compiler/CodePreprocessor.h \
    ../src/Engine/Graphics/Shaders/ShaderPreprocessor.h \
    ../src/Engine/IO/Project/Project.h \
    ../src/Engine/IO/Project/ProjectManager.h \
    ../src/Engine/Graphics/GraphicPipeline/GPPass_G.h \
    ../src/Engine/Graphics/GraphicPipeline/GPPass.h \
    ../src/Engine/Graphics/General/GLObject.h \
    ../src/Engine/Debug/ChronoGL.h \
    ../src/Engine/DataStructures/Set.h \
    ../src/Engine/IO/General/SerializableObject.h \
    ../src/Engine/Graphics/GraphicPipeline/TextureUnitManager.h \
    ../src/Engine/DataStructures/UMap.h \
    ../src/Engine/Graphics/General/Image.h \
    ../src/Engine/Components/CircleCulledRenderer.h \
    ../src/Engine/IO/Files/PrefabFile.h \
    ../src/Engine/IO/Files/SoundFile.h \
    ../src/Engine/Audio/AnonymousAudioPlayer.h \
    ../src/Engine/DataStructures/Flags.h \
    ../src/Engine/Graphics/Shaders/ShaderManager.h \
    ../src/Engine/Components/PostProcessEffect.h \
    ../src/Engine/Graphics/GraphicPipeline/GPPass_SP_PostProcessEffects.h \
    ../src/Engine/IO/Files/Path.h \
    ../src/Engine/IO/Files/ModelFile.h \
    ../src/Engine/IO/Files/MeshFile.h \
    ../src/Engine/DataStructures/Regex.h \
    ../src/Engine/IO/Files/AudioClipFile.h \
    ../src/Engine/IO/Files/FontFile.h \
    ../src/Engine/IO/Files/MaterialFile.h \
    ../src/Engine/IO/Files/ShaderProgramFile.h \
    ../src/Engine/IO/Files/Texture2DFile.h \
    ../src/Engine/IO/General/Paths.h \
    ../src/Engine/Graphics/GraphicPipeline/GPPass_RenderLayer.h \
    ../src/Engine/DataStructures/Collection.h \
    ../src/Engine/Compiler/BangPreprocessor/BangPreprocessor.h \
    ../src/Engine/Compiler/BangPreprocessor/BPReflectedVariable.h \
    ../src/Engine/Compiler/BangPreprocessor/BPReflectedStruct.h \
    ../src/Engine/Debug/OStreamOperators.h \
    ../src/Engine/IO/Files/BFile.h \
    ../src/Engine/Compiler/BangCompilerAsyncJob.h

EDITOR {
HEADERS += \
    ../src/Editor/General/GameObjectClipboard.h \
    ../src/Editor/Windows/IWindow.h \
    ../src/Editor/Windows/GameWindow.h \
    ../src/Engine/Compiler/Compiler.h \
    ../src/Engine/Compiler/BangCompiler.h \
    ../src/Editor/General/Cursor.h \
    ../src/Editor/General/Shortcut.h \
    ../src/Editor/General/IconManager.h \
    ../src/Editor/Windows/EditorWindow.h \
    ../src/Engine/Graphics/GraphicPipeline/GPPass_Selection.h \
    ../src/Editor/EditorGameObject/EditorGizmosGameObject.h \
    ../src/Editor/DragDrop/DragDropQWidget.h \
    ../src/Engine/IO/Files/AssetFileCreator.h \
    ../src/Engine/IO/Project/QtProjectManager.h \
    ../src/Editor/DragDrop/DragDropQListView.h \
    ../src/Editor/Explorer/FileReferencesManager.h \
    ../src/Editor/DragDrop/DragDropQTreeWidget.h \
    ../src/Editor/Inspector/Inspectables/Inspectable.h \
    ../src/Editor/Inspector/Inspectables/GameObjectInspectable.h \
    ../src/Editor/Inspector/Inspectables/IInspectable.h \
    ../src/Editor/Inspector/Inspectables/FileInspectable.h \
    ../src/Editor/Inspector/Inspectables/ComponentInspectable.h \
    ../src/Editor/DragDrop/DragDropQListWidget.h \
    ../src/Editor/DragDrop/DragDropAgent.h \
    ../src/Editor/DragDrop/IDragDropListener.h \
    ../src/Engine/IO/Behaviours/BehaviourRefresherTimer.h \
    ../src/Editor/DragDrop/DragDropManager.h \
    ../src/Editor/Explorer/FileSystemModel.h \
    ../src/Editor/EditorGameObject/EditorSelectionGameObject.h \
    ../src/Editor/EditorScene/EditorDebugGameObject.h \
    ../src/Engine/Graphics/Buffers/SelectionFramebuffer.h \
    ../src/Editor/EditorGameObject/EditorTranslateAxis.h \
    ../src/Editor/EditorGameObject/EditorTranslateAxisGroup.h \
    ../src/Editor/Dialogs/DialogBrowseAssetFile.h \
    ../src/Editor/Inspector/AttributeWidgets/AttributeWidget.h \
    ../src/Editor/Inspector/AttributeWidgets/AttrWidgetBool.h \
    ../src/Editor/Inspector/AttributeWidgets/AttrWidgetButton.h \
    ../src/Editor/Inspector/AttributeWidgets/AttrWidgetColor.h \
    ../src/Editor/Inspector/AttributeWidgets/AttrWidgetEnum.h \
    ../src/Editor/Inspector/AttributeWidgets/AttrWidgetFile.h \
    ../src/Editor/Inspector/AttributeWidgets/AttrWidgetFloat.h \
    ../src/Editor/Inspector/AttributeWidgets/AttrWidgetString.h \
    ../src/Editor/Inspector/AttributeWidgets/AttrWidgetVectorFloat.h \
    ../src/Editor/Inspector/AttributeWidgets/IAttrWidgetButtonListener.h \
    ../src/Editor/Inspector/Inspectables/PrefabFileInspectable.h \
    ../src/Editor/Windows/WindowEventManager.h \
    ../src/Editor/Windows/SelectProjectWindow.h \
    ../src/Editor/General/Toolbar.h \
    ../src/Editor/General/EditorState.h \
    ../src/Editor/Dialogs/GameBuildDialog.h \
    ../src/Editor/GameBuilder/GameBuilderJob.h \
    ../src/Editor/Dialogs/Dialog.h \
    ../src/Editor/General/IWindowEventManagerListener.h \
    ../src/Editor/Inspector/Inspector.h \
    ../src/Editor/Hierarchy/Hierarchy.h \
    ../src/Editor/Inspector/ComponentWidget.h \
    ../src/Editor/Console/Console.h \
    ../src/Editor/Explorer/Explorer.h \
    ../src/Editor/General/MenuBar.h \
    ../src/Editor/Explorer/ExplorerDirTree.h \
    ../src/Editor/Inspector/InspectorWidget.h \
    ../src/Editor/EditorCamera/EditorCamera.h \
    ../src/Editor/EditorScene/EditorScene.h \
    ../src/Editor/EditorGameObject/EditorBBox.h \
    ../src/Editor/EditorGameObject/EditorRotateAxisGroup.h \
    ../src/Editor/EditorGameObject/EditorRotateAxis.h \
    ../src/Editor/EditorGameObject/EditorAxisGroup.h \
    ../src/Editor/EditorGameObject/EditorAxis.h \
    ../src/Editor/EditorGameObject/EditorScaleAxisGroup.h \
    ../src/Editor/EditorGameObject/EditorScaleAxis.h \
    ../src/Editor/EditorScene/EditorFloor.h \
    ../src/Editor/Inspector/ComponentClipboard.h \
    ../src/Editor/Hierarchy/HierarchyDragDropManager.h \
    ../src/Editor/Hierarchy/HierarchyContextMenu.h \
    ../src/Editor/Explorer/ExplorerContextMenu.h \
    ../src/Editor/Inspector/ComponentWidgetContextMenu.h \
    ../src/Editor/Hierarchy/HierarchyItem.h \
    ../src/Editor/Inspector/InspectorContextMenu.h \
    ../src/Editor/General/ContextMenu.h \
    ../src/Editor/GameBuilder/GameBuilder.h \
    ../src/Editor/EditorGameObject/EditorAxisPlane.h \
    ../src/Editor/Explorer/ExplorerFileSortProxy.h \
    ../src/Editor/Inspector/AttributeWidgets/AttrWidgetInt.h \
    ../src/Editor/EditorGameObject/EditorRectTransform/EditorRectTransformGizmo.h \
    ../src/Editor/EditorGameObject/EditorRectTransform/EditorRectTransformCornerGizmo.h \
    ../src/Editor/EditorGameObject/EditorRectTransform/EditorRectTransformAnchorGizmo.h \
    ../src/Editor/EditorGameObject/EditorGizmo.h \
    ../src/Editor/DragDrop/DragDropInfo.h \
    ../src/Editor/General/EditorPlayFlow.h \
    ../src/Engine/IO/Files/FileTracker.h
}

EDITOR {
    SOURCES += \
        ../src/Editor/EditorGameObject/EditorGizmosGameObject.cpp \
        ../src/Engine/Graphics/GraphicPipeline/GPPass_Selection.cpp \
        ../src/Engine/IO/Files/AssetFileCreator.cpp \
        ../src/Editor/GameBuilder/GameBuilderJob.cpp \
        ../src/Editor/Dialogs/GameBuildDialog.cpp \
        ../src/Editor/Explorer/FileSystemModel.cpp \
        ../src/Engine/IO/Project/QtProjectManager.cpp \
        ../src/Editor/General/EditorState.cpp \
        ../src/Editor/DragDrop/DragDropManager.cpp \
        ../src/Editor/DragDrop/DragDropQWidget.cpp \
        ../src/Editor/Explorer/FileReferencesManager.cpp \
        ../src/Editor/DragDrop/DragDropQListView.cpp \
        ../src/Editor/DragDrop/DragDropQTreeWidget.cpp \
        ../src/Editor/DragDrop/DragDropQListWidget.cpp \
        ../src/Editor/DragDrop/DragDropAgent.cpp \
        ../src/Editor/DragDrop/IDragDropListener.cpp \
        ../src/Engine/IO/Behaviours/BehaviourRefresherTimer.cpp \
        ../src/Engine/Graphics/Buffers/SelectionFramebuffer.cpp \
        ../src/Editor/EditorGameObject/EditorRotateAxisGroup.cpp \
        ../src/Editor/Windows/EditorWindow.cpp \
        ../src/Editor/Dialogs/DialogBrowseAssetFile.cpp \
        ../src/Editor/Windows/SelectProjectWindow.cpp \
        ../src/Editor/Windows/WindowEventManager.cpp \
        ../src/Editor/EditorGameObject/EditorRotateAxis.cpp \
        ../src/Editor/EditorGameObject/EditorAxisGroup.cpp \
        ../src/Editor/EditorGameObject/EditorAxis.cpp \
        ../src/Editor/EditorGameObject/EditorScaleAxisGroup.cpp \
        ../src/Editor/Inspector/AttributeWidgets/IAttrWidgetButtonListener.cpp \
        ../src/Editor/EditorGameObject/EditorScaleAxis.cpp \
        ../src/Editor/EditorScene/EditorFloor.cpp \
        ../src/Editor/General/IWindowEventManagerListener.cpp \
        ../src/Editor/Inspector/Inspector.cpp \
        ../src/Editor/Hierarchy/Hierarchy.cpp \
        ../src/Editor/Inspector/ComponentWidget.cpp \
        ../src/Editor/Inspector/AttributeWidgets/AttributeWidget.cpp \
        ../src/Editor/Inspector/AttributeWidgets/AttrWidgetFloat.cpp \
        ../src/Editor/Inspector/AttributeWidgets/AttrWidgetVectorFloat.cpp \
        ../src/Editor/Console/Console.cpp \
        ../src/Editor/Inspector/AttributeWidgets/AttrWidgetEnum.cpp \
        ../src/Editor/Explorer/Explorer.cpp \
        ../src/Editor/General/MenuBar.cpp \
        ../src/Editor/Dialogs/Dialog.cpp \
        ../src/Editor/Inspector/AttributeWidgets/AttrWidgetFile.cpp \
        ../src/Editor/Explorer/ExplorerDirTree.cpp \
        ../src/Editor/Inspector/InspectorWidget.cpp \
        ../src/Editor/Inspector/AttributeWidgets/AttrWidgetString.cpp \
        ../src/Editor/EditorCamera/EditorCamera.cpp \
        ../src/Editor/EditorScene/EditorScene.cpp \
        ../src/Editor/EditorGameObject/EditorBBox.cpp \
        ../src/Editor/EditorGameObject/EditorSelectionGameObject.cpp \
        ../src/Editor/EditorScene/EditorDebugGameObject.cpp \
        ../src/Editor/EditorGameObject/EditorTranslateAxisGroup.cpp \
        ../src/Editor/EditorGameObject/EditorTranslateAxis.cpp \
        ../src/Editor/General/Toolbar.cpp \
        ../src/Editor/Inspector/AttributeWidgets/AttrWidgetButton.cpp \
        ../src/Editor/Inspector/AttributeWidgets/AttrWidgetBool.cpp \
        ../src/Editor/Inspector/AttributeWidgets/AttrWidgetColor.cpp \
        ../src/Editor/Inspector/Inspectables/Inspectable.cpp \
        ../src/Editor/Inspector/Inspectables/GameObjectInspectable.cpp \
        ../src/Editor/Inspector/Inspectables/IInspectable.cpp \
        ../src/Editor/Inspector/Inspectables/FileInspectable.cpp \
        ../src/Editor/Inspector/Inspectables/ComponentInspectable.cpp \
        ../src/Editor/Inspector/Inspectables/PrefabFileInspectable.cpp \
        ../src/Editor/Inspector/ComponentClipboard.cpp \
        ../src/Editor/Hierarchy/HierarchyDragDropManager.cpp \
        ../src/Editor/Hierarchy/HierarchyContextMenu.cpp \
        ../src/Editor/Explorer/ExplorerContextMenu.cpp \
        ../src/Editor/Inspector/ComponentWidgetContextMenu.cpp \
        ../src/Editor/Inspector/InspectorContextMenu.cpp \
        ../src/Editor/GameBuilder/GameBuilder.cpp \
        ../src/Editor/General/ContextMenu.cpp \
        ../src/Editor/Hierarchy/HierarchyItem.cpp \
        ../src/Editor/Explorer/ExplorerFileSortProxy.cpp \
        ../src/Editor/Inspector/AttributeWidgets/AttrWidgetInt.cpp \
        ../src/Editor/EditorGameObject/EditorRectTransform/EditorRectTransformGizmo.cpp \
        ../src/Editor/EditorGameObject/EditorRectTransform/EditorRectTransformCornerGizmo.cpp \
        ../src/Editor/EditorGameObject/EditorRectTransform/EditorRectTransformAnchorGizmo.cpp \
        ../src/Editor/EditorGameObject/EditorGizmo.cpp \
        ../src/Editor/EditorGameObject/EditorAxisPlane.cpp \
        ../src/Engine/IO/Files/FileTracker.cpp \
        ../src/Editor/General/EditorPlayFlow.cpp
}
######################################


# OTHER FILES #############
DISTFILES += \
    ../.gitignore \
    ../src/Engine \
    ../EngineAssets/Shaders/SelectionBuffer.frag_sel \
    ../EngineAssets/Shaders/RenderGBufferToScreen.frag_pp \
    ../EngineAssets/Shaders/G_Template.frag_g \
    ../EngineAssets/Shaders/G_Default.frag_g \
    ../EngineAssets/Shaders/SelectionBuffer.vert_sel \
    ../EngineAssets/Shaders/G_Template.vert_g \
    ../EngineAssets/Shaders/G_Default.vert_g \
    ../EngineAssets/Shaders/UI/SP_UIImage.frag_pp \
    ../EngineAssets/Shaders/Include/PointLight.glsl \
    ../EngineAssets/Shaders/Include/Main.glsl \
    ../EngineAssets/Shaders/Include/DirectionalLight.glsl \
    ../EngineAssets/Shaders/Include/G.frag_g \
    ../EngineAssets/Shaders/Include/G.vert_g \
    ../EngineAssets/Materials/RenderGBufferToScreen.bmat \
    ../EngineAssets/Materials/G_Default.bmat \
    ../EngineAssets/Materials/UI/G_UIImage.bmat \
    ../EngineAssets/Shaders/G_Missing.frag \
    ../EngineAssets/Materials/Missing.bmat \
    ../EngineAssets/Materials/SP_AmbientLight_Screen.bmat \
    ../EngineAssets/Materials/SP_SelectionEffect.bmat \
    ../EngineAssets/Materials/SP_PointLight_Screen.bmat \
    ../EngineAssets/Materials/SP_DirectionalLight_Screen.bmat \
    ../EngineAssets/Shaders/Include/SP.frag_pp \
    ../EngineAssets/Shaders/Include/SP.vert_pp \
    ../EngineAssets/Shaders/SP_DirectionalLight.frag_pp \
    ../EngineAssets/Shaders/SP_ScreenPass.vert_pp \
    ../EngineAssets/Shaders/SP_PointLight.frag_pp \
    ../EngineAssets/Shaders/SP_SelectionEffect.frag_pp \
    ../EngineAssets/Shaders/SP_Template.frag_pp \
    ../EngineAssets/Materials/G_DefaultNoSP.bmat \
    ../EngineAssets/Materials/UI/G_UIImage.bmat \
    ../EngineAssets/Materials/UI/SP_UIImage.bmat \
    ../EngineAssets/Shaders/SP_FXAA.frag_pp \
    ../EngineAssets/Shaders/Include/Common.glsl \
    ../EngineAssets/Fonts/GreatFont.bfont \
    ../EngineAssets/Fonts/HandwrittenFont.bfont \
    ../EngineAssets/Fonts/PrettyFont.bfont \
    ../EngineAssets/Fonts/UbuntuFont.bfont \
    ../EngineAssets/Camera.bmesh \
    ../EngineAssets/Cone.bmesh \
    ../EngineAssets/Cube.bmesh \
    ../EngineAssets/Plane.bmesh \
    ../EngineAssets/Pyramid.bmesh \
    ../EngineAssets/Sphere.bmesh \
    ../EngineAssets/UIPlane.bmesh \
    ../EngineAssets/Textures/AudioSourceIcon.btex2d \
    ../EngineAssets/Textures/CameraIcon.btex2d \
    ../EngineAssets/Textures/CircleIcon.btex2d \
    ../EngineAssets/Textures/DefaultUIImageTexture.btex2d \
    ../EngineAssets/Textures/DirectionalLightIcon.btex2d \
    ../EngineAssets/Textures/PointLightIcon.btex2d \
    ../EngineAssets/Textures/RectTransformAnchor.btex2d \
    ../EngineAssets/Shaders/SP_Default.vert_pp \
    ../EngineAssets/Materials/UI/G_UIText_Pass2.bmat \
    ../EngineAssets/Shaders/UI/G_UIText_Pass2.frag_g \
    ../EngineAssets/Materials/UI/G_UIText.bmat \
    ../EngineAssets/Shaders/UI/G_UIText.frag_g \
    ../EngineAssets/Shaders/SP_Default.frag_pp \
    ../EngineAssets/Shaders/G_Default.bshaderprogram \
    ../EngineAssets/Shaders/Cartoon.frag_pp \
    ../EngineAssets/Shaders/G_Missing.frag_g \
    ../EngineAssets/Shaders/InvertColors.frag_pp \
    ../EngineAssets/Shaders/Blur.frag_pp \
    ../EngineAssets/Shaders/GrayScale.frag_pp \
    ../EngineAssets/Shaders/Outline.frag_pp \
