include(../BangCommon.pri)
system(rm -f Makefile)
system(rm -f .donePreprocess)
system(cd $$PWD/.. ; sh ./scripts/preprocessHeaders.sh)

TEMPLATE = lib
INCLUDEPATH += ../include
QT += core gui opengl widgets

DoPreprocess = .donePreprocess
DoPreprocess.commands = cd $$PWD/.. ; \
                        sh ./scripts/preprocessHeaders.sh ; \
                        touch .donePreprocess
QMAKE_EXTRA_TARGETS += DoPreprocess
PRE_TARGETDEPS += DoPreprocess

CONFIG += staticlib

TARGET = $$BIN_DIR/lib/Bang

LIBS = -L$$BIN_DIR/lib/ -lBangDataStructures $$LIBS
PRE_TARGETDEPS += $$BIN_DIR/lib/libBangDataStructures.a

MOC_DIR = ../src/Qt_MOCs/

UI_DIR  = ../include/Bang

EDITOR {
    FORMS   += ../EngineAssets/EditorWindow.ui
    FORMS   += ../EngineAssets/SelectProjectWindow.ui
}

SOURCES += \
    ../src/Domain/Engine/Others/Time.cpp \
    ../src/Domain/Engine/Physics/AABox.cpp \
    ../src/Domain/Engine/Physics/Sphere.cpp \
    ../src/Domain/Engine/GameObjects/GameObject.cpp \
    ../src/Domain/Engine/GameObjects/Scene.cpp \
    ../src/Domain/Graphics/Texture.cpp \
    ../src/Domain/Graphics/VAO.cpp \
    ../src/Domain/Graphics/VBO.cpp \
    ../src/Domain/Engine/Components/Transform.cpp \
    ../src/Domain/Engine/Components/Component.cpp \
    ../src/Domain/Engine/Components/MeshRenderer.cpp \
    ../src/Domain/Engine/Components/Camera.cpp \
    ../src/Domain/Engine/Assets/Asset.cpp \
    ../src/Domain/Engine/Assets/Meshes/Mesh.cpp \
    ../src/Domain/Engine/Assets/Material.cpp \
    ../src/Domain/Engine/Components/Behaviour.cpp \
    ../src/Domain/Engine/Assets/Texture2D.cpp \
    ../src/Domain/Engine/Assets/Prefab.cpp \
    ../src/Persistence/AssetsManager.cpp \
    ../src/Domain/Engine/Others/Input.cpp \
    ../src/Persistence/Files/TextFile.cpp \
    ../src/Domain/Engine/Components/LineRenderer.cpp \
    ../src/Domain/Engine/Components/Renderer.cpp \
    ../src/Domain/Engine/Others/SystemUtils.cpp \
    ../src/Domain/Engine/Others/SingletonManager.cpp \
    ../src/Domain/Engine/Components/CircleRenderer.cpp \
    ../src/Domain/Engine/Components/SingleLineRenderer.cpp \
    ../src/Domain/Engine/Assets/Meshes/MeshFactory.cpp \
    ../src/Domain/Engine/Interfaces/ICloneable.cpp \
    ../src/View/Screen.cpp \
    ../src/Domain/Engine/Components/DirectionalLight.cpp \
    ../src/Domain/Engine/Components/Light.cpp \
    ../src/View/GameObjectClipboard.cpp \
    ../src/Domain/Engine/Components/PointLight.cpp \
    ../src/View/Application.cpp \
    ../src/Domain/Engine/Others/SceneManager.cpp \
    ../src/Domain/Engine/Components/Canvas.cpp \
    ../src/Domain/Engine/Components/UIImage.cpp \
    ../src/Domain/Engine/Components/UIRenderer.cpp \
    ../src/Domain/Graphics/FontSheetCreator.cpp \
    ../src/Domain/Engine/Assets/Font.cpp \
    ../src/Domain/Engine/Components/UIText.cpp \
    ../src/Persistence/EngineConfig.cpp \
    ../src/Domain/Engine/Assets/AudioClip.cpp \
    ../src/Domain/Engine/Components/AudioSource.cpp \
    ../src/Domain/Engine/Audio/AudioManager.cpp \
    ../src/Domain/Engine/Audio/AudioPlayerRunnable.cpp \
    ../src/Domain/Engine/Debug/Gizmos.cpp \
    ../src/Domain/Engine/Debug/Debug.cpp \
    ../src/Domain/Engine/Debug/Chrono.cpp \
    ../src/Domain/Graphics/Buffers/Framebuffer.cpp \
    ../src/Domain/Graphics/Buffers/GBuffer.cpp \
    ../src/Domain/Graphics/Shaders/Shader.cpp \
    ../src/Domain/Graphics/Shaders/ShaderProgram.cpp \
    ../src/Persistence/IO/FileReader.cpp \
    ../src/Persistence/Files/ImageFile.cpp \
    ../src/Persistence/Behaviours/BehaviourManager.cpp \
    ../src/Persistence/Behaviours/BehaviourRefresherTimer.cpp \
    ../src/Persistence/XML/XMLAttribute.cpp \
    ../src/Persistence/XML/XMLNode.cpp \
    ../src/Persistence/XML/XMLParser.cpp \
    ../src/Persistence/XML/XMLProperty.cpp \
    ../src/View/Windows/IWindow.cpp \
    ../src/View/Windows/GameWindow.cpp \
    ../src/Domain/Engine/Components/AudioListener.cpp \
    ../src/Persistence/Behaviours/BehaviourManagerStatus.cpp \
    ../src/Domain/Engine/Components/RectTransform.cpp \
    ../src/View/Cursor.cpp \
    ../src/Domain/Graphics/RenderTexture.cpp \
    ../src/Domain/Engine/Object.cpp \
    ../src/Domain/Engine/Others/GraphicPipelineDebugger.cpp \
    ../src/Domain/Engine/GraphicPipeline/GraphicPipeline.cpp \
    ../src/Domain/Engine/GraphicPipeline/GPPass_SP_DeferredLights.cpp \
    ../src/Domain/Engine/GraphicPipeline/GPPass_G_Gizmos.cpp \
    ../src/Domain/Graphics/GLContext.cpp \
    ../src/Domain/Graphics/GL.cpp \
    ../src/Domain/Engine/CodePreprocessor.cpp \
    ../src/Domain/Graphics/Shaders/ShaderPreprocessor.cpp \
    ../src/Persistence/Project/ProjectManager.cpp \
    ../src/Persistence/Project/Project.cpp \
    ../src/Persistence/Behaviours/BehaviourObjectCompileRunnable.cpp \
    ../src/Persistence/Behaviours/BehaviourMergeObjectsRunnable.cpp \
    ../src/Domain/Engine/GraphicPipeline/GPPass_G.cpp \
    ../src/Domain/Engine/GraphicPipeline/GPPass.cpp \
    ../src/Domain/Graphics/Interfaces/GLObject.cpp \
    ../src/Domain/Engine/Debug/ChronoGL.cpp \
    ../src/Domain/Engine/Interfaces/SerializableObject.cpp \
    ../src/Domain/Engine/GraphicPipeline/TextureUnitManager.cpp \
    ../src/View/Shortcut.cpp \
    ../src/Persistence/Files/ExtensionManager.cpp \
    ../src/View/IconManager.cpp \
    ../src/Domain/Engine/Image.cpp \
    ../src/Domain/Engine/Components/CircleCulledRenderer.cpp \
    ../src/Persistence/Files/PrefabFile.cpp \
    ../src/Persistence/Files/SoundFile.cpp \
    ../src/Domain/Engine/Audio/AnonymousAudioPlayer.cpp \
    ../src/Domain/Graphics/Shaders/ShaderManager.cpp \
    ../src/Domain/Engine/Components/PostProcessEffect.cpp \
    ../src/Domain/Engine/GraphicPipeline/GPPass_SP_PostProcessEffects.cpp \
    ../src/Persistence/Files/ModelFile.cpp \
    ../src/Persistence/Files/MeshFile.cpp \
    ../src/Persistence/Files/Texture2DFile.cpp \
    ../src/Persistence/Files/ShaderProgramFile.cpp \
    ../src/Persistence/Files/MaterialFile.cpp \
    ../src/Persistence/Files/AudioClipFile.cpp \
    ../src/Persistence/Files/FontFile.cpp \
    ../src/Persistence/Paths.cpp \
    ../src/Domain/Engine/GraphicPipeline/GPPass_RenderLayer.cpp \
    ../src/Domain/BangPreprocessor/BangPreprocessor.cpp \
    ../src/Domain/BangPreprocessor/BPReflectedStruct.cpp \
    ../src/Domain/Engine/Others/Compiler.cpp \
    ../src/Domain/Engine/Others/BangCompiler.cpp \
    ../src/Domain/BangPreprocessor/BPReflectedVariable.cpp \
    ../src/Persistence/Files/BFile.cpp

HEADERS +=                                                          \
    ../src/View/Application.h                                          \
    ../src/View/Screen.h                                               \
    ../src/Domain/Engine/Physics/Rect.h                                \
    ../src/Domain/Interfaces/IToString.h                               \
    ../src/Domain/Engine/Interfaces/ISceneEventListener.h              \
    ../src/Domain/Engine/GameObjects/GameObject.h                      \
    ../src/Domain/Engine/GameObjects/Scene.h                           \
    ../src/Domain/Graphics/Texture.h                                   \
    ../src/Domain/Graphics/VAO.h                                       \
    ../src/Domain/Graphics/VBO.h                                       \
    ../src/Domain/Engine/Components/Transform.h                        \
    ../src/Domain/Engine/Components/Component.h                        \
    ../src/Domain/Engine/Components/MeshRenderer.h                     \
    ../src/Domain/Engine/Components/Camera.h                           \
    ../src/Domain/Engine/Assets/Asset.h                                \
    ../src/Domain/Engine/Assets/Material.h                             \
    ../src/Domain/Engine/Assets/Meshes/Mesh.h                          \
    ../src/Domain/Engine/Components/Behaviour.h                        \
    ../src/Domain/Engine/Assets/Texture2D.h                            \
    ../src/Domain/Engine/Assets/Prefab.h                               \
    ../include/Bang/Bang.h                                             \
    ../src/Persistence/AssetsManager.h                                 \
    ../src/Domain/Engine/Others/Input.h                                \
    ../src/Domain/Engine/Components/LineRenderer.h                     \
    ../src/Domain/Engine/Components/Renderer.h                         \
    ../src/Domain/Engine/Physics/Vector3.h                             \
    ../src/Domain/Engine/Physics/Quaternion.h                          \
    ../src/Domain/Engine/Physics/Matrix4.h                             \
    ../src/Domain/Engine/Physics/Sphere.h                              \
    ../src/Domain/Engine/Others/SystemUtils.h                          \
    ../src/Domain/Engine/Others/SingletonManager.h                     \
    ../src/Domain/Engine/Components/CircleRenderer.h                   \
    ../src/Domain/Engine/Components/SingleLineRenderer.h               \
    ../src/Domain/Engine/Assets/Meshes/MeshFactory.h                   \
    ../src/Domain/Engine/Interfaces/ICloneable.h                       \
    ../src/Domain/Engine/Components/DirectionalLight.h                 \
    ../src/Domain/Engine/Components/Light.h                            \
    ../src/Domain/Engine/Components/PointLight.h                       \
    ../src/Domain/Engine/Physics/Vector4.h                             \
    ../src/Domain/Engine/Physics/Vector2.h                             \
    ../src/Domain/Engine/Physics/Color.h                               \
    ../src/Domain/Engine/Others/SceneManager.h                         \
    ../src/Domain/Engine/Components/Canvas.h                           \
    ../src/Domain/Engine/Components/UIImage.h                          \
    ../src/Domain/Engine/Components/UIRenderer.h                       \
    ../src/Domain/Graphics/FontSheetCreator.h                          \
    ../src/Domain/Engine/Assets/Font.h                                 \
    ../src/Domain/Engine/Components/UIText.h                           \
    ../src/Persistence/EngineConfig.h                                  \
    ../src/Domain/Engine/Physics/AABox.h                               \
    ../src/Domain/Engine/Assets/AudioClip.h                            \
    ../src/Domain/Engine/Components/AudioSource.h                      \
    ../src/Domain/Engine/Audio/AudioManager.h                          \
    ../src/Domain/Engine/Audio/AudioPlayerRunnable.h                   \
    ../src/Domain/Engine/DataStructures/Array.h                        \
    ../src/Domain/Engine/DataStructures/List.h                         \
    ../src/Domain/Engine/DataStructures/Map.h                          \
    ../src/Domain/Engine/DataStructures/Property.h                     \
    ../src/Domain/Engine/DataStructures/String.h                       \
    ../src/Domain/Engine/DataStructures/NamedEnum.h                    \
    ../src/Domain/Engine/Debug/Chrono.h                                \
    ../src/Domain/Engine/Debug/Debug.h                                 \
    ../src/Domain/Engine/Debug/Gizmos.h                                \
    ../src/Domain/Engine/Debug/Time.h                                  \
    ../src/Domain/Engine/DataStructures/Timer.h                        \
    ../src/Domain/Graphics/Buffers/Framebuffer.h                       \
    ../src/Domain/Graphics/Buffers/GBuffer.h                           \
    ../src/Domain/Graphics/Shaders/Shader.h                            \
    ../src/Domain/Graphics/Shaders/ShaderProgram.h                     \
    ../src/Persistence/Behaviours/BehaviourManager.h                   \
    ../src/Persistence/Behaviours/BehaviourRefresherTimer.h            \
    ../src/Persistence/IO/FileReader.h                                 \
    ../src/Persistence/Files/ImageFile.h                               \
    ../src/Persistence/XML/XMLAttribute.h                              \
    ../src/Persistence/XML/XMLNode.h                                   \
    ../src/Persistence/XML/XMLParser.h                                 \
    ../src/Persistence/XML/XMLProperty.h                               \
    ../src/Persistence/Files/TextFile.h \
    ../src/Domain/Engine/Physics/Math.h \
    ../src/Domain/Engine/Physics/Random.h \
    ../src/Persistence/Files/ExtensionManager.h \
    ../src/Domain/Engine/Components/AudioListener.h \
    ../src/Persistence/Behaviours/BehaviourManagerStatus.h \
    ../src/Domain/Engine/Components/RectTransform.h \
    ../src/Domain/Graphics/RenderTexture.h \
    ../src/Domain/Engine/Object.h \
    ../src/Domain/Engine/Others/GraphicPipelineDebugger.h \
    ../src/Domain/Engine/GraphicPipeline/GraphicPipeline.h \
    ../src/Domain/Engine/GraphicPipeline/GPPass_SP_DeferredLights.h \
    ../src/Domain/Engine/GraphicPipeline/GPPass_G_Gizmos.h \
    ../src/Domain/Graphics/GLContext.h \
    ../src/Domain/Graphics/GL.h \
    ../src/Domain/Engine/DataStructures/TypeMap.h \
    ../src/Domain/Engine/CodePreprocessor.h \
    ../src/Domain/Graphics/Shaders/ShaderPreprocessor.h \
    ../src/Persistence/Project/Project.h \
    ../src/Persistence/Project/ProjectManager.h \
    ../src/Persistence/Behaviours/BehaviourObjectCompileRunnable.h \
    ../src/Persistence/Behaviours/BehaviourMergeObjectsRunnable.h \
    ../src/Domain/Engine/GraphicPipeline/GPPass_G.h \
    ../src/Domain/Engine/GraphicPipeline/GPPass.h \
    ../src/Domain/Graphics/Interfaces/GLObject.h \
    ../src/Domain/Engine/Debug/ChronoGL.h \
    ../src/Domain/Engine/DataStructures/Set.h \
    ../src/Domain/Engine/Interfaces/SerializableObject.h \
    ../src/Domain/Engine/GraphicPipeline/TextureUnitManager.h \
    ../src/Domain/Engine/DataStructures/UMap.h \
    ../src/Domain/Engine/Image.h \
    ../src/Domain/Engine/Components/CircleCulledRenderer.h \
    ../src/Persistence/Files/PrefabFile.h \
    ../src/Persistence/Files/SoundFile.h \
    ../src/Domain/Engine/Audio/AnonymousAudioPlayer.h \
    ../src/Domain/Engine/DataStructures/Flags.h \
    ../src/Domain/Graphics/Shaders/ShaderManager.h \
    ../src/Domain/Engine/Components/PostProcessEffect.h \
    ../src/Domain/Engine/GraphicPipeline/GPPass_SP_PostProcessEffects.h \
    ../src/Persistence/Files/Path.h \
    ../src/Persistence/Files/ModelFile.h \
    ../src/Persistence/Files/MeshFile.h \
    ../src/Domain/Engine/DataStructures/Regex.h \
    ../src/Persistence/Files/AudioClipFile.h \
    ../src/Persistence/Files/FontFile.h \
    ../src/Persistence/Files/MaterialFile.h \
    ../src/Persistence/Files/ShaderProgramFile.h \
    ../src/Persistence/Files/Texture2DFile.h \
    ../src/Persistence/Paths.h \
    ../src/Domain/Engine/GraphicPipeline/GPPass_RenderLayer.h \
    ../src/Domain/Engine/DataStructures/Collection.h \
    ../src/Domain/BangPreprocessor/BangPreprocessor.h \
    ../src/Domain/BangPreprocessor/BPReflectedVariable.h \
    ../src/Domain/BangPreprocessor/BPReflectedStruct.h \
    ../src/Domain/Engine/Debug/OStreamOperators.h \
    ../src/Persistence/Files/BFile.h

EDITOR {
HEADERS += \
    ../src/View/GameObjectClipboard.h \
    ../src/View/Windows/IWindow.h \
    ../src/View/Windows/GameWindow.h \
    ../src/Domain/Engine/Others/Compiler.h \
    ../src/Domain/Engine/Others/BangCompiler.h \
    ../src/View/Cursor.h \
    ../src/View/Shortcut.h \
    ../src/View/IconManager.h \
    ../src/View/Windows/EditorWindow.h \
    ../src/Domain/Engine/GraphicPipeline/GPPass_Selection.h \
    ../src/View/EditorGameObject/EditorGizmosGameObject.h \
    ../src/View/DragDrop/DragDropQWidget.h \
    ../src/Persistence/Files/AssetFileCreator.h \
    ../src/Persistence/Project/QtProjectManager.h \
    ../src/View/DragDrop/DragDropQListView.h \
    ../src/View/Explorer/FileReferencesManager.h \
    ../src/View/DragDrop/DragDropQTreeWidget.h \
    ../src/View/Inspector/Inspectables/Inspectable.h \
    ../src/View/Inspector/Inspectables/GameObjectInspectable.h \
    ../src/View/Inspector/Inspectables/IInspectable.h \
    ../src/View/Inspector/Inspectables/FileInspectable.h \
    ../src/View/Inspector/Inspectables/ComponentInspectable.h \
    ../src/View/DragDrop/DragDropQListWidget.h \
    ../src/View/DragDrop/DragDropAgent.h \
    ../src/View/DragDrop/IDragDropListener.h \
    ../src/View/DragDrop/DragDropManager.h \
    ../src/View/Explorer/FileSystemModel.h \
    ../src/View/EditorGameObject/EditorSelectionGameObject.h \
    ../src/View/EditorScene/EditorDebugGameObject.h \
    ../src/Domain/Graphics/Buffers/SelectionFramebuffer.h              \
    ../src/View/EditorGameObject/EditorTranslateAxis.h \
    ../src/View/EditorGameObject/EditorTranslateAxisGroup.h \
    ../src/View/Dialogs/DialogBrowseAssetFile.h                        \
    ../src/View/Inspector/AttributeWidgets/AttributeWidget.h           \
    ../src/View/Inspector/AttributeWidgets/AttrWidgetBool.h            \
    ../src/View/Inspector/AttributeWidgets/AttrWidgetButton.h          \
    ../src/View/Inspector/AttributeWidgets/AttrWidgetColor.h           \
    ../src/View/Inspector/AttributeWidgets/AttrWidgetEnum.h            \
    ../src/View/Inspector/AttributeWidgets/AttrWidgetFile.h            \
    ../src/View/Inspector/AttributeWidgets/AttrWidgetFloat.h           \
    ../src/View/Inspector/AttributeWidgets/AttrWidgetString.h          \
    ../src/View/Inspector/AttributeWidgets/AttrWidgetVectorFloat.h     \
    ../src/View/Inspector/AttributeWidgets/IAttrWidgetButtonListener.h \
    ../src/View/Inspector/Inspectables/PrefabFileInspectable.h    \
    ../src/View/Windows/WindowEventManager.h \
    ../src/View/Windows/SelectProjectWindow.h \
    ../src/View/Toolbar.h \
    ../src/View/EditorState.h \
    ../src/View/Dialogs/GameBuildDialog.h \
    ../src/View/GameBuilderJob.h \
    ../src/View/Dialogs/Dialog.h \
    ../src/View/Interfaces/IWindowEventManagerListener.h \
    ../src/View/Inspector/Inspector.h \
    ../src/View/Hierarchy/Hierarchy.h \
    ../src/View/Inspector/ComponentWidget.h \
    ../src/View/Console/Console.h \
    ../src/View/Explorer/Explorer.h \
    ../src/View/MenuBar.h \
    ../src/View/Explorer/ExplorerDirTree.h \
    ../src/View/Inspector/InspectorWidget.h \
    ../src/View/EditorCamera/EditorCamera.h \
    ../src/View/EditorScene/EditorScene.h \
    ../src/View/EditorGameObject/EditorBBox.h \
    ../src/View/EditorGameObject/EditorRotateAxisGroup.h \
    ../src/View/EditorGameObject/EditorRotateAxis.h \
    ../src/View/EditorGameObject/EditorAxisGroup.h \
    ../src/View/EditorGameObject/EditorAxis.h \
    ../src/View/EditorGameObject/EditorScaleAxisGroup.h \
    ../src/View/EditorGameObject/EditorScaleAxis.h \
    ../src/View/EditorScene/EditorFloor.h \
    ../src/View/Inspector/ComponentClipboard.h \
    ../src/View/Hierarchy/HierarchyDragDropManager.h \
    ../src/View/Hierarchy/HierarchyContextMenu.h \
    ../src/View/Explorer/ExplorerContextMenu.h \
    ../src/View/Inspector/ComponentWidgetContextMenu.h \
    ../src/View/Hierarchy/HierarchyItem.h \
    ../src/View/Inspector/InspectorContextMenu.h \
    ../src/View/ContextMenu.h \
    ../src/Domain/Engine/Others/GameBuilder.h \
    ../src/View/EditorGameObject/EditorAxisPlane.h \
    ../src/View/Explorer/ExplorerFileSortProxy.h \
    ../src/View/Inspector/AttributeWidgets/AttrWidgetInt.h \
    ../src/View/EditorGameObject/EditorRectTransform/EditorRectTransformGizmo.h \
    ../src/View/EditorGameObject/EditorRectTransform/EditorRectTransformCornerGizmo.h \
    ../src/View/EditorGameObject/EditorRectTransform/EditorRectTransformAnchorGizmo.h \
    ../src/View/EditorGameObject/EditorGizmo.h \
    ../src/View/DragDrop/DragDropInfo.h \
    ../src/View/EditorPlayFlow.h \
    ../src/Persistence/FileTracker.h
}

EDITOR {
    SOURCES += \
        ../src/View/EditorGameObject/EditorGizmosGameObject.cpp \
        ../src/Domain/Engine/GraphicPipeline/GPPass_Selection.cpp \
        ../src/Persistence/Files/AssetFileCreator.cpp \
        ../src/View/GameBuilderJob.cpp \
        ../src/View/Dialogs/GameBuildDialog.cpp \
        ../src/View/Explorer/FileSystemModel.cpp \
        ../src/Persistence/Project/QtProjectManager.cpp \
        ../src/View/EditorState.cpp \
        ../src/View/DragDrop/DragDropManager.cpp \
        ../src/View/DragDrop/DragDropQWidget.cpp \
        ../src/View/Explorer/FileReferencesManager.cpp \
        ../src/View/DragDrop/DragDropQListView.cpp \
        ../src/View/DragDrop/DragDropQTreeWidget.cpp \
        ../src/View/DragDrop/DragDropQListWidget.cpp \
        ../src/View/DragDrop/DragDropAgent.cpp \
        ../src/View/DragDrop/IDragDropListener.cpp \
        ../src/Domain/Graphics/Buffers/SelectionFramebuffer.cpp \
        ../src/View/EditorGameObject/EditorRotateAxisGroup.cpp \
        ../src/View/Windows/EditorWindow.cpp \
        ../src/View/Dialogs/DialogBrowseAssetFile.cpp \
        ../src/View/Windows/SelectProjectWindow.cpp \
        ../src/View/Windows/WindowEventManager.cpp \
        ../src/View/EditorGameObject/EditorRotateAxis.cpp \
        ../src/View/EditorGameObject/EditorAxisGroup.cpp \
        ../src/View/EditorGameObject/EditorAxis.cpp \
        ../src/View/EditorGameObject/EditorScaleAxisGroup.cpp \
        ../src/View/Inspector/AttributeWidgets/IAttrWidgetButtonListener.cpp \
        ../src/View/EditorGameObject/EditorScaleAxis.cpp \
        ../src/View/EditorScene/EditorFloor.cpp \
        ../src/View/Interfaces/IWindowEventManagerListener.cpp \
        ../src/View/Inspector/Inspector.cpp \
        ../src/View/Hierarchy/Hierarchy.cpp \
        ../src/View/Inspector/ComponentWidget.cpp \
        ../src/View/Inspector/AttributeWidgets/AttributeWidget.cpp \
        ../src/View/Inspector/AttributeWidgets/AttrWidgetFloat.cpp \
        ../src/View/Inspector/AttributeWidgets/AttrWidgetVectorFloat.cpp \
        ../src/View/Console/Console.cpp \
        ../src/View/Inspector/AttributeWidgets/AttrWidgetEnum.cpp \
        ../src/View/Explorer/Explorer.cpp \
        ../src/View/MenuBar.cpp \
        ../src/View/Dialogs/Dialog.cpp \
        ../src/View/Inspector/AttributeWidgets/AttrWidgetFile.cpp \
        ../src/View/Explorer/ExplorerDirTree.cpp \
        ../src/View/Inspector/InspectorWidget.cpp \
        ../src/View/Inspector/AttributeWidgets/AttrWidgetString.cpp \
        ../src/View/EditorCamera/EditorCamera.cpp \
        ../src/View/EditorScene/EditorScene.cpp \
        ../src/View/EditorGameObject/EditorBBox.cpp \
        ../src/View/EditorGameObject/EditorSelectionGameObject.cpp \
        ../src/View/EditorScene/EditorDebugGameObject.cpp \
        ../src/View/EditorGameObject/EditorTranslateAxisGroup.cpp \
        ../src/View/EditorGameObject/EditorTranslateAxis.cpp \
        ../src/View/Toolbar.cpp \
        ../src/View/Inspector/AttributeWidgets/AttrWidgetButton.cpp \
        ../src/View/Inspector/AttributeWidgets/AttrWidgetBool.cpp \
        ../src/View/Inspector/AttributeWidgets/AttrWidgetColor.cpp \
        ../src/View/Inspector/Inspectables/Inspectable.cpp \
        ../src/View/Inspector/Inspectables/GameObjectInspectable.cpp \
        ../src/View/Inspector/Inspectables/IInspectable.cpp \
        ../src/View/Inspector/Inspectables/FileInspectable.cpp \
        ../src/View/Inspector/Inspectables/ComponentInspectable.cpp \
        ../src/View/Inspector/Inspectables/PrefabFileInspectable.cpp \
        ../src/View/Inspector/ComponentClipboard.cpp \
        ../src/View/Hierarchy/HierarchyDragDropManager.cpp \
        ../src/View/Hierarchy/HierarchyContextMenu.cpp \
        ../src/View/Explorer/ExplorerContextMenu.cpp \
        ../src/View/Inspector/ComponentWidgetContextMenu.cpp \
        ../src/View/Inspector/InspectorContextMenu.cpp \
        ../src/Domain/Engine/Others/GameBuilder.cpp \
        ../src/View/ContextMenu.cpp \
        ../src/View/Hierarchy/HierarchyItem.cpp \
        ../src/View/Explorer/ExplorerFileSortProxy.cpp \
        ../src/View/Inspector/AttributeWidgets/AttrWidgetInt.cpp \
        ../src/View/EditorGameObject/EditorRectTransform/EditorRectTransformGizmo.cpp \
        ../src/View/EditorGameObject/EditorRectTransform/EditorRectTransformCornerGizmo.cpp \
        ../src/View/EditorGameObject/EditorRectTransform/EditorRectTransformAnchorGizmo.cpp \
        ../src/View/EditorGameObject/EditorGizmo.cpp \
        ../src/View/EditorGameObject/EditorAxisPlane.cpp \
        ../src/Persistence/FileTracker.cpp \
        ../src/View/EditorPlayFlow.cpp
}
######################################


# OTHER FILES #############
OTHER_FILES += \
    ../.gitignore \
    ../Assets/Engine/qdarkstyle/style.qss \
    ../src/Domain \
    ../Assets/Scenes/sceneTest1.scene \
    ../Assets/Scenes/sceneFileFormat.txt \
    ../Assets/Scenes/assetsTest.assets \
    ../Assets/Assets/Meshes/Pyramid.obj \
    ../Assets/Engine/Materials \
    ../Assets/Behaviours/TestBehaviour.cpp / \
    ../Assets/Behaviours/TestBehaviour.h / \
    ../Assets/Behaviours/LookAtLuigi.h \
    ../Assets/Behaviours/LookAtLuigi.cpp \
    ../Assets/Engine/Meshes/Pyramid.obj \
    ../Assets/Engine/Meshes/Cube.obj \
    ../Assets/Engine/Meshes/Cone.obj \
    ../Assets/Engine/Meshes/Sphere.obj \
    ../Assets/Engine/Meshes/Cube.bmesh \
    ../Assets/Engine/Meshes/Cone.bmesh \
    ../Assets/Engine/Meshes/Sphere.bmesh \
    ../Assets/Engine/Meshes/Pyramid.bmesh \
    ../Assets/Engine/Shaders/SP_DirectionalLight.frag_pp \
    ../Assets/Engine/Shaders/G_Default.frag_g \
    ../Assets/Engine/Shaders/G_Default.vert_g \
    ../Assets/Materials/luigiMaterial.bmat \
    ../Assets/Materials/testMaterial.bmat \
    ../Assets/Materials/testMaterial2.bmat \
    ../Assets/Engine/Shaders/SelectionBuffer.frag_pp \
    ../Assets/Engine/Shaders/RenderGBufferToScreen.frag_pp \
    ../Assets/Engine/Shaders/SP_PointLight.frag_pp \
    ../Assets/Scenes/tmp.bscene \
    ../Assets/Scenes/test2.bscene \
    ../Assets/Engine/Materials/G_Default.bmat \
    ../Assets/Engine/Materials/SP_EditorEffects.bmat \
    ../Assets/Engine/Materials/SP_DirectionalLight.bmat \
    ../Assets/Engine/Materials/SP_PointLight.bmat \
    ../Assets/Behaviours/RandomScale.h \
    ../Assets/Behaviours/RandomScale.cpp \
    ../Assets/Materials/victor.bmat \
    ../Assets/Engine/Meshes/Plane.bmesh \
    ../Assets/Meshes/luigiMesh.bmesh \
    ../Assets/Meshes/boyMesh.bmesh \
    ../Assets/Textures/victor.btex2d \
    ../Assets/Textures/woodTexture.btex2d \
    ../Assets/Textures/luigiTexture.btex2d \
    ../Assets/Textures/carpetTexture.btex2d \
    ../Assets/Scenes/test.bscene \
    ../Assets/Engine/Textures/DirectionalLightIcon.btex2d \
    ../Assets/Engine/Textures/PointLightIcon.btex2d \
    ../Assets/Engine/Shaders/G.vert_g \
    ../Assets/Engine/Shaders/SP.vert_pp \
    ../Assets/Engine/Shaders/SP.frag_pp \
    ../Assets/Engine/Shaders/Include/G.frag_g \
    ../Assets/Engine/Shaders/Include/SP.frag_pp \
    ../Assets/Engine/Shaders/Include/G.vert_g \
    ../Assets/Engine/Shaders/Include/SP.vert_pp \
    ../Assets/Engine/Shaders/Include/Common.glsl \
    ../Assets/Engine/Shaders/Include/PointLight.glsl \
    ../Assets/Engine/Shaders/Include/DirectionalLight.glsl \
    ../Assets/Engine/Materials/SP_DirectionalLight_Screen.bmat \
    ../Assets/Engine/Materials/SP_PointLight_Screen.bmat \
    ../Assets/Engine/Shaders/UI/SP_UIImage.frag_pp \
    ../Assets/Engine/Materials/UI/SP_UIImage.bmat \
    ../Assets/Engine/Shaders/SP_RenderBackground.frag_pp \
    ../Assets/Engine/Shaders/Include/Main.glsl \
    ../Assets/Engine/Shaders/SelectionBuffer.vert_sel \
    ../Assets/Engine/Shaders/SP_SelectionEffect.frag_pp \
    ../Assets/Engine/Materials/SP_MeshPass.bmat \
    ../Assets/Engine/Materials/RenderGBufferToScreen.bmat \
    ../Assets/Engine/Shaders/SP_ScreenPass.vert_pp \
    ../Assets/Engine/Materials/SP_SelectionEffect.bmat \
    ../Assets/Engine/Shaders/UI/G_UIText.frag_g \
    ../Assets/Engine/Materials/UI/G_UIText.bmat \
    ../EngineAssets/Shaders/SelectionBuffer.frag_sel \
    ../EngineAssets/Shaders/RenderGBufferToScreen.frag_pp \
    ../EngineAssets/Shaders/G_Template.frag_g \
    ../EngineAssets/Shaders/G_Default.frag_g \
    ../EngineAssets/Shaders/SelectionBuffer.vert_sel \
    ../EngineAssets/Shaders/G_Template.vert_g \
    ../EngineAssets/Shaders/G_Default.vert_g \
    ../EngineAssets/Shaders/UI/SP_UIImage.frag_pp \
    ../EngineAssets/Shaders/Include/PointLight.glsl \
    ../EngineAssets/Shaders/Include/Main.glsl \
    ../EngineAssets/Shaders/Include/DirectionalLight.glsl \
    ../EngineAssets/Shaders/Include/G.frag_g \
    ../EngineAssets/Shaders/Include/G.vert_g \
    ../EngineAssets/Materials/RenderGBufferToScreen.bmat \
    ../EngineAssets/Materials/G_Default.bmat
######################################

DISTFILES += \
    ../EngineAssets/Materials/UI/G_UIImage.bmat \
    ../EngineAssets/Shaders/G_Missing.frag \
    ../EngineAssets/Materials/Missing.bmat \
    ../EngineAssets/Materials/SP_AmbientLight_Screen.bmat \
    ../EngineAssets/Materials/SP_SelectionEffect.bmat \
    ../EngineAssets/Materials/SP_PointLight_Screen.bmat \
    ../EngineAssets/Materials/SP_DirectionalLight_Screen.bmat \
    ../EngineAssets/Shaders/Include/SP.frag_pp \
    ../EngineAssets/Shaders/Include/SP.vert_pp \
    ../EngineAssets/Shaders/SP_DirectionalLight.frag_pp \
    ../EngineAssets/Shaders/SP_ScreenPass.vert_pp \
    ../EngineAssets/Shaders/SP_PointLight.frag_pp \
    ../EngineAssets/Shaders/SP_SelectionEffect.frag_pp \
    ../EngineAssets/Shaders/SP_Template.frag_pp \
    ../EngineAssets/Materials/G_DefaultNoSP.bmat \
    ../EngineAssets/Materials/UI/G_UIImage.bmat \
    ../EngineAssets/Materials/UI/SP_UIImage.bmat \
    ../EngineAssets/Shaders/SP_FXAA.frag_pp \
    ../EngineAssets/Shaders/Include/Common.glsl \
    ../EngineAssets/Fonts/GreatFont.bfont \
    ../EngineAssets/Fonts/HandwrittenFont.bfont \
    ../EngineAssets/Fonts/PrettyFont.bfont \
    ../EngineAssets/Fonts/UbuntuFont.bfont \
    ../EngineAssets/Meshes/Camera.bmesh \
    ../EngineAssets/Meshes/Cone.bmesh \
    ../EngineAssets/Meshes/Cube.bmesh \
    ../EngineAssets/Meshes/Plane.bmesh \
    ../EngineAssets/Meshes/Pyramid.bmesh \
    ../EngineAssets/Meshes/Sphere.bmesh \
    ../EngineAssets/Meshes/UIPlane.bmesh \
    ../EngineAssets/Textures/AudioSourceIcon.btex2d \
    ../EngineAssets/Textures/CameraIcon.btex2d \
    ../EngineAssets/Textures/CircleIcon.btex2d \
    ../EngineAssets/Textures/DefaultUIImageTexture.btex2d \
    ../EngineAssets/Textures/DirectionalLightIcon.btex2d \
    ../EngineAssets/Textures/PointLightIcon.btex2d \
    ../EngineAssets/Textures/RectTransformAnchor.btex2d \
    ../EngineAssets/Shaders/SP_Default.vert_pp \
    ../EngineAssets/Materials/UI/G_UIText_Pass2.bmat \
    ../EngineAssets/Shaders/UI/G_UIText_Pass2.frag_g \
    ../EngineAssets/Materials/UI/G_UIText.bmat \
    ../EngineAssets/Shaders/UI/G_UIText.frag_g \
    ../EngineAssets/Shaders/SP_Default.frag_pp \
    ../EngineAssets/Shaders/G_Default.bshaderprogram \
    ../EngineAssets/Shaders/Cartoon.frag_pp \
    ../EngineAssets/Shaders/G_Missing.frag_g \
    ../EngineAssets/Shaders/InvertColors.frag_pp \
    ../EngineAssets/Shaders/Blur.frag_pp \
    ../EngineAssets/Shaders/GrayScale.frag_pp \
    ../EngineAssets/Shaders/Outline.frag_pp \
